package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1



/**
 * Festivalmedia generated by hbm2java
 */
public class Festivalmedia  implements java.io.Serializable {


     private Integer id;
     private Festival festival;
     private Media media;

    public Festivalmedia() {
    }

    public Festivalmedia(Festival festival, Media media) {
       this.festival = festival;
       this.media = media;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Media getMedia() {
        return this.media;
    }
    
    public void setMedia(Media media) {
        this.media = media;
    }




}


