package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Integer id;
     private Location location;
     private String name;
     private Date datetimeStart;
     private Date datetimeEnd;
     private Integer ticketsPerUser;
     private Long views;
     private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
     private Set<Socialnetwork> socialnetworks = new HashSet<Socialnetwork>(0);
     private Set<Festivalday> festivaldays = new HashSet<Festivalday>(0);
     private Set<Festivalmedia> festivalmedias = new HashSet<Festivalmedia>(0);

    public Festival() {
    }

    public Festival(Location location, String name, Date datetimeStart, Date datetimeEnd, Integer ticketsPerUser, Long views, Set<Feedback> feedbacks, Set<Socialnetwork> socialnetworks, Set<Festivalday> festivaldays, Set<Festivalmedia> festivalmedias) {
       this.location = location;
       this.name = name;
       this.datetimeStart = datetimeStart;
       this.datetimeEnd = datetimeEnd;
       this.ticketsPerUser = ticketsPerUser;
       this.views = views;
       this.feedbacks = feedbacks;
       this.socialnetworks = socialnetworks;
       this.festivaldays = festivaldays;
       this.festivalmedias = festivalmedias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDatetimeStart() {
        return this.datetimeStart;
    }
    
    public void setDatetimeStart(Date datetimeStart) {
        this.datetimeStart = datetimeStart;
    }
    public Date getDatetimeEnd() {
        return this.datetimeEnd;
    }
    
    public void setDatetimeEnd(Date datetimeEnd) {
        this.datetimeEnd = datetimeEnd;
    }
    public Integer getTicketsPerUser() {
        return this.ticketsPerUser;
    }
    
    public void setTicketsPerUser(Integer ticketsPerUser) {
        this.ticketsPerUser = ticketsPerUser;
    }
    public Long getViews() {
        return this.views;
    }
    
    public void setViews(Long views) {
        this.views = views;
    }
    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set<Socialnetwork> getSocialnetworks() {
        return this.socialnetworks;
    }
    
    public void setSocialnetworks(Set<Socialnetwork> socialnetworks) {
        this.socialnetworks = socialnetworks;
    }
    public Set<Festivalday> getFestivaldays() {
        return this.festivaldays;
    }
    
    public void setFestivaldays(Set<Festivalday> festivaldays) {
        this.festivaldays = festivaldays;
    }
    public Set<Festivalmedia> getFestivalmedias() {
        return this.festivalmedias;
    }
    
    public void setFestivalmedias(Set<Festivalmedia> festivalmedias) {
        this.festivalmedias = festivalmedias;
    }




}


