package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Set<Festival> festivals = new HashSet<Festival>(0);

    public Location() {
    }

    public Location(String description, Set<Festival> festivals) {
       this.description = description;
       this.festivals = festivals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Festival> getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Set<Festival> festivals) {
        this.festivals = festivals;
    }




}


