package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Media generated by hbm2java
 */
public class Media  implements java.io.Serializable {


     private Integer id;
     private String path;
     private Set<Festivalmedia> festivalmedias = new HashSet<Festivalmedia>(0);

    public Media() {
    }

    public Media(String path, Set<Festivalmedia> festivalmedias) {
       this.path = path;
       this.festivalmedias = festivalmedias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public Set<Festivalmedia> getFestivalmedias() {
        return this.festivalmedias;
    }
    
    public void setFestivalmedias(Set<Festivalmedia> festivalmedias) {
        this.festivalmedias = festivalmedias;
    }




}


