package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Performer generated by hbm2java
 */
public class Performer  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Festivaldayperformer> festivaldayperformers = new HashSet<Festivaldayperformer>(0);

    public Performer() {
    }

	
    public Performer(int id) {
        this.id = id;
    }
    public Performer(int id, String name, Set<Festivaldayperformer> festivaldayperformers) {
       this.id = id;
       this.name = name;
       this.festivaldayperformers = festivaldayperformers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Festivaldayperformer> getFestivaldayperformers() {
        return this.festivaldayperformers;
    }
    
    public void setFestivaldayperformers(Set<Festivaldayperformer> festivaldayperformers) {
        this.festivaldayperformers = festivaldayperformers;
    }




}


