package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private Integer id;
     private User userByFestivalFk;
     private User userByUserFk;
     private Integer value;

    public Rating() {
    }

    public Rating(User userByFestivalFk, User userByUserFk, Integer value) {
       this.userByFestivalFk = userByFestivalFk;
       this.userByUserFk = userByUserFk;
       this.value = value;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByFestivalFk() {
        return this.userByFestivalFk;
    }
    
    public void setUserByFestivalFk(User userByFestivalFk) {
        this.userByFestivalFk = userByFestivalFk;
    }
    public User getUserByUserFk() {
        return this.userByUserFk;
    }
    
    public void setUserByUserFk(User userByUserFk) {
        this.userByUserFk = userByUserFk;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }




}


