package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private Integer id;
     private Type type;
     private Integer volume;
     private Long price;
     private Set<TicketFestivalday> ticketFestivaldays = new HashSet<TicketFestivalday>(0);
     private Set<Ticketreservation> ticketreservations = new HashSet<Ticketreservation>(0);

    public Ticket() {
    }

    public Ticket(Type type, Integer volume, Long price, Set<TicketFestivalday> ticketFestivaldays, Set<Ticketreservation> ticketreservations) {
       this.type = type;
       this.volume = volume;
       this.price = price;
       this.ticketFestivaldays = ticketFestivaldays;
       this.ticketreservations = ticketreservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public Integer getVolume() {
        return this.volume;
    }
    
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Set<TicketFestivalday> getTicketFestivaldays() {
        return this.ticketFestivaldays;
    }
    
    public void setTicketFestivaldays(Set<TicketFestivalday> ticketFestivaldays) {
        this.ticketFestivaldays = ticketFestivaldays;
    }
    public Set<Ticketreservation> getTicketreservations() {
        return this.ticketreservations;
    }
    
    public void setTicketreservations(Set<Ticketreservation> ticketreservations) {
        this.ticketreservations = ticketreservations;
    }




}


