package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1



/**
 * Ticketreservation generated by hbm2java
 */
public class Ticketreservation  implements java.io.Serializable {


     private Integer id;
     private Ticket ticket;
     private User user;
     private String status;

    public Ticketreservation() {
    }

    public Ticketreservation(Ticket ticket, User user, String status) {
       this.ticket = ticket;
       this.user = user;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


