package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1



/**
 * TicketFestivalday generated by hbm2java
 */
public class TicketFestivalday  implements java.io.Serializable {


     private Integer id;
     private Festivalday festivalday;
     private Ticket ticket;

    public TicketFestivalday() {
    }

    public TicketFestivalday(Festivalday festivalday, Ticket ticket) {
       this.festivalday = festivalday;
       this.ticket = ticket;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Festivalday getFestivalday() {
        return this.festivalday;
    }
    
    public void setFestivalday(Festivalday festivalday) {
        this.festivalday = festivalday;
    }
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }




}


