package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Type() {
    }

    public Type(String name, Set<Ticket> tickets) {
       this.name = name;
       this.tickets = tickets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}


