package database_stuff;
// Generated Jan 28, 2017 8:06:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String username;
     private String email;
     private byte[] password;
     private String phoneNumber;
     private Boolean reservationsBanned;
     private Date lastLoginDatetime;
     private Set<Feedback> feedbacks = new HashSet<Feedback>(0);
     private Set<Registration> registrations = new HashSet<Registration>(0);
     private Set<Ticketreservation> ticketreservations = new HashSet<Ticketreservation>(0);
     private Set<Notification> notifications = new HashSet<Notification>(0);
     private Set<Rating> ratingsForFestivalFk = new HashSet<Rating>(0);
     private Set<Rating> ratingsForUserFk = new HashSet<Rating>(0);
     private Set<Admin> admins = new HashSet<Admin>(0);

    public User() {
    }

    public User(String firstName, String lastName, String username, String email, byte[] password, String phoneNumber, Boolean reservationsBanned, Date lastLoginDatetime, Set<Feedback> feedbacks, Set<Registration> registrations, Set<Ticketreservation> ticketreservations, Set<Notification> notifications, Set<Rating> ratingsForFestivalFk, Set<Rating> ratingsForUserFk, Set<Admin> admins) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.username = username;
       this.email = email;
       this.password = password;
       this.phoneNumber = phoneNumber;
       this.reservationsBanned = reservationsBanned;
       this.lastLoginDatetime = lastLoginDatetime;
       this.feedbacks = feedbacks;
       this.registrations = registrations;
       this.ticketreservations = ticketreservations;
       this.notifications = notifications;
       this.ratingsForFestivalFk = ratingsForFestivalFk;
       this.ratingsForUserFk = ratingsForUserFk;
       this.admins = admins;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPassword() {
        return this.password;
    }
    
    public void setPassword(byte[] password) {
        this.password = password;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Boolean getReservationsBanned() {
        return this.reservationsBanned;
    }
    
    public void setReservationsBanned(Boolean reservationsBanned) {
        this.reservationsBanned = reservationsBanned;
    }
    public Date getLastLoginDatetime() {
        return this.lastLoginDatetime;
    }
    
    public void setLastLoginDatetime(Date lastLoginDatetime) {
        this.lastLoginDatetime = lastLoginDatetime;
    }
    public Set<Feedback> getFeedbacks() {
        return this.feedbacks;
    }
    
    public void setFeedbacks(Set<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }
    public Set<Ticketreservation> getTicketreservations() {
        return this.ticketreservations;
    }
    
    public void setTicketreservations(Set<Ticketreservation> ticketreservations) {
        this.ticketreservations = ticketreservations;
    }
    public Set<Notification> getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set<Notification> notifications) {
        this.notifications = notifications;
    }
    public Set<Rating> getRatingsForFestivalFk() {
        return this.ratingsForFestivalFk;
    }
    
    public void setRatingsForFestivalFk(Set<Rating> ratingsForFestivalFk) {
        this.ratingsForFestivalFk = ratingsForFestivalFk;
    }
    public Set<Rating> getRatingsForUserFk() {
        return this.ratingsForUserFk;
    }
    
    public void setRatingsForUserFk(Set<Rating> ratingsForUserFk) {
        this.ratingsForUserFk = ratingsForUserFk;
    }
    public Set<Admin> getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set<Admin> admins) {
        this.admins = admins;
    }




}


